safe:        false
auto:        true
server:      false
server_port: 4000
base-url:    /

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    true
markdown:    rdiscount
permalink:   /stash/:categories/:year/:month/:title/

date_format: "%d %b %Y"

exclude:
    - Makefile
    - lib

categories:
    - projects

title: Andrew Stone
author: Andrew Stone

nav_pages:
    - name: Home
      url: index
    - name: Projects
      url: projects
    - name: About
      url: about
    - name: The Site
      url: this-site

js:
    - harmony.js
    - hijax.js
    - brushes/chrome.js
    - brushes/circles.js
    - brushes/longfur.js
    - brushes/ribbon.js
    - monkey/Array.js
    - monkey/Object.js
    - cornify.js
    - tracking.js

css:
    - reset.css
    - tags.css
    - main.css
    - pages.css
    - syntax.css
    
