safe:        false
base-url:    /

source:      .
destination: ./_site
plugins:     ./_plugins

lsi:         false
highlighter: pygments
markdown:    kramdown
permalink:   /stash/:categories/:year/:month/:title/

date_format: "%d %b %Y"

exclude:
    - Makefile
    - lib

categories:
    - projects

title: Andrew Stone
author: Andrew Stone

nav_pages:
    - name: Home
      url: index
    - name: Projects
      url: projects
    - name: Posts
      url: posts
    - name: About
      url: about
    - name: The Site
      url: this-site

js:
    - harmony.js
    - hijax.js
    - brushes/chrome.js
    - brushes/circles.js
    - brushes/longfur.js
    - brushes/ribbon.js
    - monkey/Array.js
    - monkey/Object.js
    - cornify.js

css:
    - reset.css
    - tags.css
    - main.css
    - pages.css
    - posts.css
    - syntax.css
